### ISSUE TITLE
Define fullscreen in terms of feature policy

### ISSUE THREAD

**Issue by clelland** [whatwg/fullscreen#106]
https://wicg.github.io/feature-policy informally declares Fullscreen to be a policy-controlled feature (and Chrome currently implements it as such). I'm trying to work out what it would take to make that more formal.

Currently, I have:

 * Define fullscreen as a policy-controlled feature in this spec, referencing the FP spec.
 * Update 'allowed to use' in HTML to query a document's FP (already monkey-patched in FP).
 * Update privacy and security in this spec to mention alternative ways that fullscreen could be enabled.

I'm sure I'm missing something big still :)

**Comment by annevk** [comment]
I don't understand how 4 in https://wicg.github.io/feature-policy/#integration-with-html works.

How many implementers have committed to feature policy?

**Comment by clelland** [comment]
> I don't understand how 4 in https://wicg.github.io/feature-policy/#integration-with-html works.

The idea is that:

 * A document has a feature policy
 * "`allowfullscreen`" indicates the policy-controlled feature named "`fullscreen`"
 * The policy may or may not enable fullscreen for an origin, specifically the document's origin in this case.
 * By replacing step 4 (and 5 now, I think), "allowed to use" becomes:

1. If document has no browsing context, then return false.
2. If document's browsing context's active document is not document, then return false.
3. If document's browsing context is a top-level browsing context, then return true.
4. If document’s feature policy enables the feature indicated by allowattribute for the origin of document, then return true.
5. Return false.

(If FP controls the features completely, then we'd probably want to get rid of step 3 as well, since FP will also handle that case)

I've filed https://github.com/WICG/feature-policy/issues/95 to track actually making it clearer.

> How many implementers have committed to feature policy?

Chrome, certainly -- I don't know that there is any public commitment from other implementers. That does raise the question of whether it's better to include language for browsers which don't support FP, or to let PRs like this sit until there is general support. I don't know what the right answer to that is, though.

**Comment by annevk** [comment]
https://github.com/WICG/gesture-delegation/issues/13 suggests Safari might be on board with Feature Policy. Is that correct @othermaciej? Haven't seen public signals from Mozilla yet. I'd like at least two implementors on board before integrating this everywhere. It'd be rather costly to revert it all.

As for that new algorithm, I don't think that works as-is. It doesn't deal with "_allowattribute_ flag" for instance or the referenced issue about `allowfullscreen` needing to be dynamic. Probably best to figure that out in a separate issue?

**Comment by othermaciej** [comment]
We don't have a specific implementation plan or timeline yet, but I think we generally like the idea.
