### ISSUE TITLE
Unable to zoom and scroll in mobile browsers when in full screen.

### ISSUE THREAD

**Issue by agnelvishal** [whatwg/fullscreen#110]
For example when I use chrome in android and load https://mdn.mozillademos.org/en-US/docs/Web/CSS/:fullscreen$samples/Example?revision=1312011 I am able to zoom without full screen but not in full screen.
Any help will be appreciated.

**Comment by foolip** [comment]
@agnelvishal does this work on other mobile browsers?

**Comment by agnelvishal** [comment]
No. It does not work on Firefox and Opera too

**Comment by agnelvishal** [comment]
The updated version of issue is at https://github.com/whatwg/fullscreen/issues/111
