### ISSUE TITLE
Dispatch fullscreenchange on the fullscreen element

### ISSUE THREAD

**Issue by annevk** [whatwg/fullscreen#122]
This proposal has rough implementer agreement:

* `fullscreenchange` should dispatch on the element that goes fullscreen and have bubbles and composed set to true. That way it's still compatible with `Document`.
* We should move `onfullscreenchange` to the `GlobalEventHandlers` mixin (using a partial mixin I suppose).
* `fullscreenerror` and `onfullscreenerror` remain as-is, which is a little awkward.

This will help when there are a lot of shadow roots that each need to observe when the document goes fullscreen. Rather than having a single target with loads of listener that all need to run each time, we'd end up with lots of targets with few listeners.

Background: https://github.com/w3c/webcomponents/issues/614.

**Comment by foolip** [comment]
> `fullscreenchange` should dispatch on the element that goes fullscreen and have bubbles and composed set to true. That way it's still compatible with `Document`.

This is now the case, see https://fullscreen.spec.whatwg.org/#run-the-fullscreen-steps which was  done in https://github.com/whatwg/fullscreen/pull/90.

> We should move `onfullscreenchange` to the `GlobalEventHandlers` mixin (using a partial mixin I suppose).

>`fullscreenerror` and `onfullscreenerror` remain as-is, which is a little awkward.

Actually fullscreenerror is also dispatched on the element now. The event handler properties are on both `Element` and `Document`, so moving those to `GlobalEventHandlers` would be fine, which would also make `window.onfullscreenchange` work.

@rniwa @upsuper does that last change sound good to you?

**Comment by annevk** [comment]
I think the main weird thing with `fullscreenerror` is that when you remove the element it wouldn't end up on document, but maybe that's okay.

Anyway, completely forgot that we already did all this. Seems shadow tree integration is further along than expected!

**Comment by upsuper** [comment]
> does that last change sound good to you?

Yeah, that sounds good.

> I think the main weird thing with `fullscreenerror` is that when you remove the element it wouldn't end up on document, but maybe that's okay.

Hmmm... do we reset node document of element when removing it? I cannot find any place in steps to remove. But I do find that we change the node document before invoking removing steps when moving element, which means the event would be dispatched to the target document... which doesn't sound great.

**Comment by upsuper** [comment]
This is now fixed and implemented on Gecko as well. I guess we can close it now.
