### ISSUE TITLE
Request Fullscreen take additional options

### ISSUE THREAD

**Issue by dtapuska** [whatwg/fullscreen#123]
There are multiple uses of fullscreen, videos, gaming, etc. Sometimes an app may wish to just be transient full screen and want to just hide the status and URL bar.

Does it make sense to augment requestFullScreen with a dictionary so that applications can possibly not set 

This can be done in native apps on Android by not specifying [SYSTEM_UI_FLAG_HIDE_NAVIGATION](https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_HIDE_NAVIGATION)

As well iOS has some APIs such as [hidesBottomBarWhenPushed](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621863-hidesbottombarwhenpushed) and [prefersstatusbarhidden](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden)

**Comment by annevk** [comment]
Maybe, if we do anything here we should reconcile it a bit with `window.open()` perhaps.

**Comment by upsuper** [comment]
I don't think I fully understand what you want here.

Fullscreen means making the content take the whole screen area for it to display, and having UI hidden is an requirement for that to happen. But it seems you are proposing just hide the UI stuff?

Native apps on mobile system are kind of different, because those apps almost always already take the majority of the viewport, and thus hiding the system bars really means it's taking the whole screen. However, on desktop platforms, there are browser UI, as well as system UI, and browser may not take the whole desktop area from the beginning (when they are not maximized).

So it is unclear to me what you really want. from that analogy

**Comment by dtapuska** [comment]
A page may wish to go fullscreen but allow an app to go back easily. On devices with physical buttons for back/home it is easy but on pages that have overlays for that it may be harder for the user to detect how to go back. So I'm proposing a property like `prefersNavigationBar` which would not set the HIDE_NAVIGATION flag.

Samsung's browser always does this; it never hides the navigation bar however Chrome does. So I'm not certain how we can reconcile the default.

**Comment by winstonchen** [comment]
@dtapuska In response to your comment, "Samsung's browser always does this; it never hides the navigation bar...", Samsung Internet auto hides the navigation in some scenarios (ie. videos). 

@foolip We will get back to you on your questions.

**Comment by dtapuska** [comment]
@winstonchen  Yes I saw this and should have been more descriptive. Fundamentally the webpage has the best knowledge of whether it is a immersive experience or not and that is what this request for options is about.

**Comment by foolip** [comment]
Screenshots of Chrome and Samsung Internet showing the difference would be super helpful :)

**Comment by winstonchen** [comment]
![video](https://user-images.githubusercontent.com/6033563/38697512-44d2bc30-3e60-11e8-8c6b-fd6204a97c1e.jpg)
![regularfullscreen](https://user-images.githubusercontent.com/6033563/38697543-550e204e-3e60-11e8-92d4-af7762567586.jpg)

**Comment by winstonchen** [comment]
From Chome. First is video, second is the full screen demo from above.
![chrome_video](https://user-images.githubusercontent.com/6033563/38697784-f22ed986-3e60-11e8-988f-b27cdf973146.jpg)
![chrome_fullscreen](https://user-images.githubusercontent.com/6033563/38697787-f43c39f8-3e60-11e8-8976-dc1b647bd5c3.jpg)

**Comment by foolip** [comment]
Aha, so it comes down do whether soft keys are visible? I guess controlling the status bar at the top is also something that native apps can do?

While coming up with terminology that makes sense across devices is going to be tricky, I think it makes very good sense that the web platform should be able to do this.

@jernoble, are there similar choices made for Safari's fullscreen on iOS, that could be influenced by the web page with an options dictionary of some description?

**Comment by jernoble** [comment]
@foolip, yes a native app on iOS can choose whether the status bar is visible (and what style the status bar takes on) during a presentation.  The only fullscreen mode available on iOS Safari is the <video> fullscreen mode, so it's not really relevant here; Safari will always display the status bar and fullscreen media controls in that case.

**Comment by jernoble** [comment]
@foolip 
> While coming up with terminology that makes sense across devices is going to be tricky, I think it makes very good sense that the web platform should be able to do this.

I tend to disagree. I personally would be very concerned that a web page would be able to present itself in fullscreen mode and disable only affordance (soft keys) which allow the user to switch apps.

**Comment by foolip** [comment]
@jernoble

> The only fullscreen mode available on iOS Safari is the fullscreen mode, so it's not really relevant here; Safari will always display the status bar and fullscreen media controls in that case.

Is the video case special, or do you mean that even with `randomElement.webkitRequestFullscreen()`, the status bar will always be visible?

> I personally would be very concerned that a web page would be able to present itself in fullscreen mode and disable only affordance (soft keys) which allow the user to switch apps.

As you can tell from the screenshots, different Android browsers have gone with different behavior here, and it sounds like Safari iOS is "always display", so yeah, product teams have disagreed about this. (I wasn't aware of this difference at all before this thread, so have no background about Chrome's behavior.)

Whatever the *default* is, a way to get the other behavior could make sense:
* If no soft keys are shown by default, make them visible (uncontroversial, I presume).
* If they *are*, hide them, but perhaps only if the user has jumped through a number of hoops, probably browser-specific, perhaps something like the web app being "installed".

Whether any browser maker is in the second category I don't know, and certainly if the product decision is to *always* show certain bits of UI no matter what, then those options become meaningless to implement for those browsers. Is that the case for Safari iOS?

Samsung folks, what would you like?

**Comment by jernoble** [comment]
@foolip 
> Is the video case special, or do you mean that even with randomElement.webkitRequestFullscreen(), the status bar will always be visible?

I mean that iOS Safari doesn't support the "Fullscreen API" specification; the only fullscreen mode available is the old, unspecified `HTMLVideoElement.webkitEnterFullscreen()` one, that takes a `<video>` element into a fullscreen mode and adds native media controls (regardless of the `controls` attribute).

> If no soft keys are shown by default, make them visible (uncontroversial, I presume).

Indeed.

> If they are, hide them, but perhaps only if the user has jumped through a number of hoops, probably browser-specific, perhaps something like the web app being "installed".

Indeed as well.

**Comment by jackpalmer1** [comment]
Are there any updates on this? We need this for our webapp. We want to request fullscreen while keeping the OS UI in place, and hiding only the browser UI.

**Comment by smaug----** [comment]
@dtapuska will Chrome implement support for the options also on desktop? Or is this mobile only thingie?

**Comment by dtapuska** [comment]
We support the options but they don't have any effect on Desktop. So if you feature detect that the querying the attribute from the dictionary it will pass on desktop. 

@foolip Thoughts on this? It is not impossible to change but I didn't feel there was a need since it was only a hint.

**Comment by smaug----** [comment]
Not honoring the flag on desktop feels odd. If one passes { navigationUI: "show" } and the feature is supported, but navigation UI isn't shown, I'd consider that a bug in the implementation.
What if the enum didn't have value "show", only "auto" and "hide"?

**Comment by dtapuska** [comment]
The spec text allows for the user agent to override the requested behavior: "User agents are always free to honor user preference over the application’s. "

**Comment by smaug----** [comment]
I don't expect all the random web devs to read the spec. The APIs themselves should be clear and easy to understand.

**Comment by smaug----** [comment]
Something which tells that the API is just a hint. Currently "show" and "hide" are like commands. If I see navigationUI: hide, I sure think navigation UI must be hidden.

{ preferredNavigationUI: "auto"|"hide"|"show"} ?

**Comment by dtapuska** [comment]
Mozzila posed navigaitonUI in #129. Chrome's original proposal was `prefersNavigationBar` as a `boolean`

@smaug---- @upsuper @annevk .. I'm not opposed to adding preferrred to the attribute name. But would like comments from the original ones that proposed it.

**Comment by smaug----** [comment]
Having unclear conventions elsewhere doesn't mean we need to use such convention here too. Explicit and clear APIs are, well, explicit and clear.

**Comment by annevk** [comment]
I somewhat disagree that adding "prefers" or "preferred" makes it any clearer what is going on. Verbosity is an important consideration too.

**Comment by foolip** [comment]
https://fullscreen.spec.whatwg.org/#dictdef-fullscreenoptions was introduced in https://github.com/whatwg/fullscreen/pull/129.
