### ISSUE TITLE
Dialog while in fullscreen causes fullscreenElement to return null?

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#13]
https://fullscreen.spec.whatwg.org/#dom-document-fullscreenelement

> The fullscreenElement attribute's getter must return the top element of the context object's top layer if that element has its fullscreen flag set, and null otherwise.

Similar to https://github.com/whatwg/fullscreen/issues/10 and https://github.com/whatwg/fullscreen/issues/12

**Comment by foolip** [comment]
Maybe it would be useful to have an internal definition that corresponds to `fullscreenElement` that could be used in other places to make it more clear which element in the top layer stack is special.

**Comment by annevk** [comment]
Yeah, what would a good definition be? The "topmost element within /document/'s top layer that has its fullscreen flag set"?

**Comment by foolip** [comment]
Yeah, sounds unambiguous, perhaps with an ", if any" at the end.
