### ISSUE TITLE
Travis build failed after 06c6e071f71baf391e7f2de74214e068099025fd

### ISSUE THREAD

**Issue by dtapuska** [whatwg/fullscreen#136]
@foolip 
After commit 06c6e071f71baf391e7f2de74214e068099025fd

The travis CI bot failed...
https://travis-ci.org/whatwg/fullscreen/builds/422060260?utm_source=github_status&utm_medium=notification

So I presume the change didn't deploy.

**Comment by foolip** [comment]
That issue was fixed and the change is now deployed!
