### ISSUE TITLE
Simplify to "unfullscreen exitDoc" in "exit fullscreen"?

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#14]
https://fullscreen.spec.whatwg.org/#exit-fullscreen

At the very end, it seems like "Let element be exitDoc's fullscreen element" and "Unfullscreen element within exitDoc" ought to be equivalent to "unfullscreen exitDoc" given the current definition of [collect ancestors](https://fullscreen.spec.whatwg.org/#collect-ancestors).

As written, a reader (like me) might otherwise wonder if *exitDoc* could have any fullscreen element after the steps or not.

**Comment by annevk** [comment]
Would that not break due to 8.3?

**Comment by foolip** [comment]
Oh, wait a second, this is the set of documents where we used to pop one element from the fullscreen element stack, isn't it? That potentially includes a document with more than one element on the stack, so I'm just confused. Closing this.
