### ISSUE TITLE
Rephrase: 3.12 While the first element in fullscreenElements is ...

### ISSUE THREAD

**Issue by ChangWanHong** [whatwg/fullscreen#144]
https://github.com/whatwg/fullscreen/blob/7ecd70946501abb8692bbf8ce72fa2b8d3ccf3ac/review-drafts/2019-01.bs#L331

IM Humble and not english fluent O, it might be not correct sentence. Easily, there are no condition to exit this While loop. I think writer's purpose was that if first element in "fullscreenElements" is in a nested browsing context: append browsing context container and its ancestors browsing context container recursively.

A implementation: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/fullscreen/fullscreen.cc?q=fullscreen.cc&sq=package:chromium&dr&l=706

I think it should be changed correct sentence to fulfill logical completeness. As I'm not english native, maybe I have misunderstanding on that. Please correct me if I'm wrong.

**Comment by upsuper** [comment]
It should probably be "the last element" instead.

**Comment by ChangWanHong** [comment]
@upsuper Can I make a PR based on your suggestion? It would be my first commit of whatwg :)

**Comment by annevk** [comment]
@ChangWanHong you sure can! @foolip will help with review and such. Also please feel free to add your name to the Acknowledgments section.

**Comment by ChangWanHong** [comment]
Could someone help me? master(HEAD:https://github.com/whatwg/fullscreen/commit/7ecd70946501abb8692bbf8ce72fa2b8d3ccf3ac) branch building emits some errors.
```
$ make local
bikeshed spec fullscreen.bs fullscreen.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"
LINK ERROR: Multiple possible 'browsing context' dfn refs for '/'.
Arbitrarily chose https://html.spec.whatwg.org/multipage/browsers.html#browsing-context
The following refs show up multiple times in their spec, in a way that Bikeshed can't distinguish between. Either create a manual link, or ask the spec maintainer to add disambiguating attributes (usually a for='' attribute to all of them).
spec:html; type:dfn; for:/; text:browsing context
  https://html.spec.whatwg.org/multipage/browsers.html#browsing-context
  https://html.spec.whatwg.org/multipage/window-object.html#window-bc
<a data-link-for="/" data-link-type="dfn" data-lt="browsing context">browsing context</a>
LINK ERROR: Multiple possible 'browsing contexts' dfn refs for '/'.
Arbitrarily chose https://html.spec.whatwg.org/multipage/browsers.html#browsing-context
The following refs show up multiple times in their spec, in a way that Bikeshed can't distinguish between. Either create a manual link, or ask the spec maintainer to add disambiguating attributes (usually a for='' attribute to all of them).
spec:html; type:dfn; for:/; text:browsing context
  https://html.spec.whatwg.org/multipage/browsers.html#browsing-context
  https://html.spec.whatwg.org/multipage/window-object.html#window-bc
<a data-link-for="/" data-link-type="dfn" data-lt="browsing contexts">browsing contexts</a>
 ✔  Successfully generated, with 2 linking errors
```

Is it ok with 2 linking errors like log above? I don't have any local changes.
