### ISSUE TITLE
MDN Cross-Reference Docs Clarification on fullscreenchange

### ISSUE THREAD

**Issue by richardbushell** [whatwg/fullscreen#148]
Hopefully, someone can give a definitive clarification on a current query I have on fullscreenchange.

I believe, if I understand the current spec correctly, that in a simple case, when any element enters or exits fullscreen, then there is just ONE fullscreenchange event fired, and that it is always fired directly at the target element ONLY. That will bubble back to window. Can someone definitively confirm that is correct as per the current spec, and as implemented by all modern browsers, as I believe there may have been changes made in this regard in that last year or two.

MDN reference here:-
https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange
states that TWO independent events are fired (one at the element and one at the document)

Of course, I realise that the Living Standard spec is evolving and should always be consulted, but MDN has obviously been unified as the go-to "general" source by many developers, and their reference seems at odds with my current understanding of the spec.  I have a few fullscreen api related bug reports and PRs filed with third-party JS libraries, and a couple of bug reports with browsers too, so I want to be absolutely sure that there is only ONE fullscreenchange EVENT fired.

Can anybody please clarify definitively.

**Comment by upsuper** [comment]
Yes, there should be only one `fullscreenchange` event for entering and exiting fullscreen each time. The even is dispatched to the target element (and bubble all the way up to the window) by default. There is one exception that, when exiting fullscreen, if the element has been disconnected from the document, the event would be fired to the document. But either case, there is only one event.

I guess we can close this issue now?

**Comment by richardbushell** [comment]
Thank you, that confirms my own understanding too. Is there an official liaison between the whatwg fullscreen contributors and other mainstream information channels such as MDN to update deprecated or incorrect information when spec developments evolve? It would be good to know if there's a current mechanism to do so, or should third-parties, such as myself, chase/implement this directly on MDN?

**Comment by upsuper** [comment]
You can do that yourself, or you can file bugs to MDN to ask them to update via "Feedback / Report a content problem" on their interface.

Traditionally, MDN team updates pages of features when Firefox ships them, and there is a flag on Mozilla's bugzilla for them to track that. I guess maybe other browsers have similar team work together with Mozilla's team nowadays hopefully?

**Comment by richardbushell** [comment]
OK, thanks. I will chase this up directly with MDN. Closing now.

**Comment by SDP190** [comment]
@richardbushell hi, I just came across this misleading MDN document you mentioned, and I even opened a SO issue [here](https://stackoverflow.com/questions/58582260/html-full-screen-change-event-behavior) regarding the exact confusion you mentioned, however did you get in contact with them?
