### ISSUE TITLE
"Fullscreen Element" defintion not exported?

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/fullscreen#150]
The "fullscreen element" definition has `data-noexport` attribute on it, which I think is preventing other specs from referencing it (it's not in the BikeShed dataset). Is there some reason why `data-noexport` is there? I'd like to reference  "fullscreen element" from the Screen Orientation spec.

**Comment by annevk** [comment]
Generally that's done when it's not a primitive other specifications necessarily should build on, i.e., private state. Could you elaborate a bit on what you are looking for here?

**Comment by marcoscaceres** [comment]
The Screen Orientation spec says: 

> As a pre-lock condition, a user agent MAY restrict locking the screen orientation exclusively to when the top-level browsing context's document's fullscreen element is not null. When that pre-lock condition applies, whenever the document's fullscreen element is empty and a screen orientation lock is applied, the user agent MUST lock the orientation of the document to the document's default orientation.

Happy to change it to something else, like generalize it to “is full screen” or whatever is best.

**Comment by foolip** [comment]
https://fullscreen.spec.whatwg.org/#dom-document-fullscreen uses the fullscreen element directly. I suppose that exposing https://fullscreen.spec.whatwg.org/#fullscreen-element might allow other specs to set it, which would probably be difficult to do correctly, so we could expose a read-only notion for it.

@annevk I wouldn't be particularly concerned about other specs trying to set the fullscreen element and just remove `data-noexport`. Would you do the same, or do you think a "document is fullscreen" notion would be better?

**Comment by annevk** [comment]
@foolip seems fine, also depends a bit on the number of expected callers I suppose.

**Comment by foolip** [comment]
@marcoscaceres https://fullscreen.spec.whatwg.org/#fullscreen-element is now exported. Let me know if that doesn't fix the problem.

**Comment by marcoscaceres** [comment]
excellent, thanks for exporting it.
