### ISSUE TITLE
Please clarify on README the standard status

### ISSUE THREAD

**Issue by ppKrauss** [whatwg/fullscreen#166]
It is a public discussion, public standard-body, ... Need some basic "public disclaimer" about **risk**. 

* W3C plans: `fullscreen` will become  a W3C recommendation?

* `fullscreen`  is accepted in many browsers, so  we can say that `fullscreen`  is a [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard)?

... The Mozzila's [docs/Web/API/Fullscreen_API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Browser_compatibility) say that is *"Deprecated. Not for use in new websites."*.

**Comment by annevk** [comment]
It only says that for the `fullscreen` attribute, which is indeed marked historical by the standard as well.

If you're unfamiliar with the WHATWG, I recommend reading https://whatwg.org/faq and related documents on that site.

**Comment by ppKrauss** [comment]
Thanks @annevk. [Wikipedia](https://en.wikipedia.org/wiki/WHATWG#Transition_of_HTML_Publication_to_WHATWG) showed me good news,

> On 28 May 2019, the W3C announced that WHATWG would be the sole publisher of the HTML and DOM standards. 

Congratulations!  Well,  only to confirm that is it: <br/> &nbsp; the *HTML5 standard*, in nowadays, is not W3C, is a WHATWG standard.

PS:  I checked the FAQ, and it say nothing about it.

**Comment by annevk** [comment]
I'm not sure how that relates, but okay, happy that helps.
