### ISSUE TITLE
Requesting fullscreen on the current fullscreen element should be an error

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#17]
In the current spec, when the content request fullscreen on the current fullscreen element, the call would be accepted, and a `fullscreenchange` event is fired without actually changing anything. It doesn't seem to make much sense to me.

`fullscreenchange`, as its name, should indicate that something is just changed. If nothing changes, we should fire `fullscreenerror` instead.

**Comment by foolip** [comment]
Step 7.5.2 of `requestFullscreen()` already says "If element is doc's fullscreen element, terminate these subsubsteps. Note: No need to notify observers when nothing has changed."

I think there are two cases to distinguish here:
 1. `requestFullscreen()` is called twice from the same input event handler, perhaps by different listeners or perhaps by broken fallback code that ends up calling both a prefixed and unprefixed API.
 2. A second `requestFullscreen()` call after the fullscreen transition is complete.

In both cases it would make sense, IMHO, to resolve the fulfill the promise, in which case also firing `fullscreenerror` would be odd.

**Comment by upsuper** [comment]
> Step 7.5.2 of requestFullscreen() already says "If element is doc's fullscreen element, terminate these subsubsteps. Note: No need to notify observers when nothing has changed."

This seems to be something annevk forgot to move or remove after fixing #5 

> perhaps by broken fallback code that ends up calling both a prefixed and unprefixed API

I would say this is impossible, because calling a nonexist function in JS would always through a TypeError, which stops any further code to be executed. Thus it dosen't make sense to call different API functions sequentially.

But, yeah, it seems to make sense otherwise.

I was thinking about the original restriction that we would reject a fullscreen request when the target element is an ancestor of the current fullscreen element. As we have removed that restriction, it probably doesn't make much sense now to reject anything because of this kind of reasons.

**Comment by annevk** [comment]
> This seems to be something annevk forgot to move or remove after fixing #5 

You closed this issue, but does this still need to be fixed somehow? Not entirely sure what is wrong.

**Comment by foolip** [comment]
I think fulfilling the promise is the reasonable thing to do, and is what the spec does. The only (reasonable) options for the events are firing a bogus `fullscreenchange` event or not firing any event at all, and the spec does not fire an event. This all looks good to me, but please correct me if I've misunderstood some detail.

**Comment by upsuper** [comment]
Right, I agree that we don't need any change here. I did misunderstand something.
