### ISSUE TITLE
Styles of former fullscreen elements

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#18]
In the current spec, the `:fullscreen` pseudo-class only applies to the current fullscreen element. It means, if the document has been in fullscreen, and the content requests fullscreen on another element, the previous fullscreen element would still in the top layer, but no longer have fullscreen styles applied.

This seems broken to me. I think an element should have either the full set of fullscreen styles as well as top layer styles, or none of them.

It seems to me there are three ways to solve this:

1. apply `:fullscreen` to all elements with fullscreen flag set instead of only the topmost one
2. add another pseudo-class for selecting elements in the top layer with fullscreen flag set
3. restore the fullscreen element stack concept, and only put the topmost element to the top layer

Personally, I prefer (3), because it seems to need the least change to our current impl, and is also most compatible with the current behavior. I don't really believe (1) or (2) could break any real website, though.

**Comment by foolip** [comment]
What has changed since https://www.w3.org/Bugs/Public/show_bug.cgi?id=27865 to shift the balance towards keeping the fullscreen element stack, for you?

Is there a practical problem with the current spec? Does it matter if there are a bunch of elements in the top layer where `:fullscreen` does not match? Normally the topmost element should obscure everything else anyway, right?

**Comment by upsuper** [comment]
Almost everything has changed, doesn't it?

Now we do not stop fullscreen request for elements which are not descendant of the current fullscreen element, which means the inconsistency between case 1 and case 2 no longer exists. Also we resolved to make the topmost top layer element obscure everything else, so the issue of case 3 doesn't exist any more, either.

In addition, at that time, the top layer and the fullscreen element stack are synchronous (when there is no `<dialog>`) which seems to be redundant, and is not what I'm proposing here. I propose that we should only put the topmost element of fullscreen element stack to the top layer, instead of all of them.

The issue is the style. In the spec, value of `position` other than `fixed` and `absolute` will be computed to `absolute` for top layer elements, while we force `fixed` to `:fullscreen`. Also the geometry dimensions are weird that, elements in the top layer has `left`, `right`, `top` set to 0, while we set all four dimensions to 0 for `:fullscreen`.

Obscuring things only means that they won't get focus, not that they are invisible, nor they are not accessible from the script. Generally, the elements are not visible, but authors may make the fullscreen element as well as the `::backdrop` pseudo-element transparent to uncover the things underneath. It could also happen when one of the ancestors of the fullscreen element or the element itself has `display: none`. Moreover, the script may also want to get the bounding rect of the elements in question.

**Comment by foolip** [comment]
> Almost everything has changed, hasn't it?

I meant to ask what it was that changed your mind. Maybe just unforseen consequences of the spec changes?

Certainly there are differences between having all nested fullscreen elements in the top layer and having just one, but shouldn't it almost always be the case that the fullscreen element obscures everything else, so that it doesn't matter?

It seems to me that another possible fix here would be to make the special rendering for the elements in the top layer apply only to the topmost element. In other words, where the spec says "An element in a top layer has the following characteristics" it could instead apply those rules only to the topmost element.

**Comment by upsuper** [comment]
> I meant to ask what it was that changed your mind. Maybe just unforseen consequences of the spec changes?

Well, probably yes.

> Certainly there are differences between having all nested fullscreen elements in the top layer and having just one, but shouldn't it almost always be the case that the fullscreen element obscures everything else, so that it doesn't matter?

I've mentioned that it matters because of the value of the style properties.

> It seems to me that another possible fix here would be to make the special rendering for the elements in the top layer apply only to the topmost element. In other words, where the spec says "An element in a top layer has the following characteristics" it could instead apply those rules only to the topmost element.

I don't think that works considering <dialog>, where all instances underneath are still visible, though inert.

**Comment by foolip** [comment]
> I've mentioned that it matters because of the values of the style properties vary.

Right, but do you believe that this is going to break existing content, or that the risk is higher than usual?

**Comment by upsuper** [comment]
I don't think that would break things, but the leaving a broken style state there just doesn't make sense. Also changing this may simplify the implementation.

**Comment by foolip** [comment]
Very well, what spec change do you propose? Is it only to keep track of the fullscreen elements in a separate stack while keeping all of the other recent changes?

**Comment by upsuper** [comment]
I don't really get your meaning... But anyway, I propose that we track elements which request fullscreen in a separate stack, then remove the previous "fullscreen element" from, and add the new "fullscreen element" to the top layer when we touch that stack via `requestFullscreen()` or `exitFullscreen()`.

**Comment by foolip** [comment]
What I'd like to know if this amounts to just reverting the spec to the previous shape, or what exactly it means in all of the little details.

**Comment by upsuper** [comment]
Reverting to use fullscreen element stack instead of top layer with fullscreen flag to manager the elements. In addition, add a sentence somewhere stays that when the head of the fullscreen element stack changes, remove the previous head from the top layer and add the new head into it.

**Comment by annevk** [comment]
What, you were the one that made us merge them in the first place. Sigh.

**Comment by foolip** [comment]
Could we fix this by just making changes to the rules about what style applies to the various elements in the top layer?

**Comment by upsuper** [comment]
Do you mean, make `:fullscreen` match all elements in top layer with fullscreen flag? I'm concerned that could be a breaking change, as people may use `querySelector(":fullscreen")` to select the topmost one.

**Comment by foolip** [comment]
Since we have a single `Document.fullscreenElement`, I think `:fullscreen` should keep its current definition, matching at most one element per document, but we can make whatever other changes are necessary to top layer to make the style be what it needs to be.

I can't make a very concrete proposal, because the problem still isn't very clear to me, other than that the computed style can now be different from before the changes, and this can be observable. Some examples of where it'll result in unexpected results might help.

**Comment by upsuper** [comment]
> What, you were the one that made us merge them in the first place. Sigh.

Sorry about that. I'm proposing the reverse way because I see some issues here that I didn't see before.

Also note that, this issue actually exists before we do the merge when we tried to sync the two stacks.

If I noticed this before, I probably would propose this way directly instead of proposing merging them...

**Comment by upsuper** [comment]
> I can't make a very concrete proposal, because the problem still isn't very clear to me, other than that the computed style can now be different from before the changes, and this can be observable. Some examples of where it'll result in unexpected results might help.

Well, the problem is the observable and even visible broken style.

You can compare this page https://output.jsbin.com/xahifiyitu in different browsers. It seems to me that the behavior of IE/Edge is most sensible. They use the first solution I mentioned above, and thus they return three elements for `document.querySelectorAll(':fullscreen')`.

It is a breaking change to the spec, but IE/Edge successfully shipping it may indicate that not too many authors rely on the spec behavior here. I'd be fine to see the spec gets changed this way instead of what I previously proposed here.

**Comment by foolip** [comment]
OK, so to summarize, the only change would be to make `:fullscreen` match any element with the fullscreen flag set? That seems OK, even if it's a bit weird that we'll have a single `Document.fullscreenElement` and in some cases `document.querySelector(':fullscreen')` will not return that element.

**Comment by upsuper** [comment]
Yes.

**Comment by foolip** [comment]
Anne, WDYT?

**Comment by annevk** [comment]
Seems a little weird. Do we need a new pseudo-class that only matches the top element?

**Comment by upsuper** [comment]
I don't think we need that before we actually get such request. As elements below are normally invisible, authors may not really want to sepcify styles differently.
