### ISSUE TITLE
Make fullscreenElement and fullscreenEnabled [Replaceable]?

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#2]
https://fullscreen.spec.whatwg.org/#api

There are sites that do funny things that write to `Document.fullscreenEnabled`.

From lego.com (http://cache.lego.com/r/www/r/mediaplayer/ko-KR/services/mediaplayerapi.ashx?t=635642663650000000)

```
t.fullscreenElement = t.fullscreenElement || []
```

where `t` is `document`.

From http://justdancenow.com/ (http://jdnowweb-s.cdn.ubi.com/prod/20150505_1450/web/js/application.min.js)

```
document.fullscreenEnabled = !!(document.fullscreenEnabled || document.mozFullScreenEnabled || document.msFullscreenEnabled || document.documentElement.webkitRequestFullScreen);
```

This throws in strict mode.

It's not clear how widespread such usage is. There is a risk to making `fullscreenElement` `[Replaceable]`, namely that in a browser that only has the unprefixed API, it would be impossible to observe later changes to `fullscreenElement`. Making the setter do nothing would be a more conservative fix here.

**Comment by annevk** [comment]
@upsuper any thoughts?

**Comment by upsuper** [comment]
Both usages do not seem to be very widespread. I didn't find any tutorial shows them, but I do see there is some code does this. Given that it only throws with strict mode, it's probably not a big issue. It would be great if we have data about how widespread those usages are, combined with strict mode.

I'm not familiar with how DOM APIs normally handle this kind of issues, but it seems to me that, if we want to be conservative, making the setters do nothing sounds like a reasonable compromise. But personally, I hope we could simply keep them readonly.

**Comment by upsuper** [comment]
OK, we eventually want to do this before we ship unprefixed Fullscreen API.

Microsoft just reached out to us about unprefixing stuff, and according to their information, this is one of the main reasons make them decide to step back and disable unprefixed Fullscreen API they have been shipping for around a year.

**Comment by annevk** [comment]
Interesting, I'll add it right now.

**Comment by upsuper** [comment]
I don't think we want `[Replaceable]` here, because in that case, the script may never be able to get the corresponding attributes again.

I think we want a dummy setter for the attributes rather than `[Replaceable]`. Not sure whether we have syntax for that.

**Comment by annevk** [comment]
Oooh, the setter must be a no-op?

**Comment by upsuper** [comment]
Yes.

**Comment by annevk** [comment]
So is it a problem that IDL still tries to coerce to a boolean and an Element? Or should any value be ignored by the setter?

**Comment by annevk** [comment]
That is, do we want
```webidl
  attribute boolean fullscreenEnabled;
  attribute Element? fullscreenElement;
```
or
```webidl
  attribute any fullscreenEnabled;
  attribute any fullscreenElement;
```
as they have slightly different effects.

**Comment by annevk** [comment]
Also paging @Ms2ger, @bzbarsky, and @heycam in case they know of similar places where we do this already.

**Comment by upsuper** [comment]
I believe any value should be ignored by the setter, because otherwise people would never be able to query the current value of those attributes again (unless they expicitly `delete`, I suppose, which is not something we should expect).

**Comment by upsuper** [comment]
Oh, I see what you meant. Not sure about that, then.

**Comment by foolip** [comment]
No-op setters of the current type (`boolean` and `Element?`) would suffice for the two snippets at the top of this issue, right?

@upsuper, have you tested those two sites with `[Replaceable]`? It could be that if we're lucky, it just happens to work well enough, but in general the no-op setter seems like lower risk.

**Comment by upsuper** [comment]
> No-op setters of the current type (`boolean` and `Element?`) would suffice for the two snippets at the top of this issue, right?

I'm not familiar with how WebIDL works in terms of type-checking, but I wonder would `t.fullscreenElement = t.fullscreenElement || []` work with `Element?`?

> have you tested those two sites with [Replaceable]? 

I haven't. Having a no-op setter is trivial from impl's view, and looks low risk, so I'd go that way directly.

**Comment by foolip** [comment]
Ah, `t.fullscreenElement = t.fullscreenElement || []` would throw an exception if `t.fullscreenElement` is null.

Using type `any` for these attributes is very low risk, but also very sad to see stuck forever. Maybe we could do it but add deprecation messages to the setter and measure usage, to see how far we are from usage where just sticking with the current spec would be acceptable from a compat perspective? I don't mind if the spec comes along for the ride as well, as long as we don't close the door on a sane spec before we have some usage data.

**Comment by upsuper** [comment]
@heycam could we probably add something like `[DummySetter]` to the WebIDL?

**Comment by heycam** [comment]
Yeah, we can add a new extended attribute to ignore assignments to these readonly IDL attributes.  This is only an issue in strict mode, right?

**Comment by annevk** [comment]
I'd prefer `[Noopsetter]` btw. And yeah, only affects strict mode as stated in OP.

**Comment by heycam** [comment]
Ah, the lego.com site mentioned in the OP would also throw in non-strict mode, since it's trying to assign a value of the wrong type.  I was maybe going to suggest just making the attribute writable and have the prose for the setter do nothing, but that doesn't work for wrong value types being assigned.

**Comment by upsuper** [comment]
Yeah, we'll probably need to make `fullscreenElement` `any`... but `fullscreenEnabled` should be fine.

**Comment by heycam** [comment]
`[LenientSetter]` works by returning early before trying to convert the assigned value to an IDL value, so that shouldn't be needed.
