### ISSUE TITLE
Propose not to render ::backdrop if the corresponding element is not rendered

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#20]
The current spec says:
> An element in a top layer ... is not rendered if it, or an ancestor, has the display property set to none.

It is not quite clear to me whether its corresponding `::backdrop` should be rendered in that case.

The current impls of top layer disagree with each other. The Blink impl for `<dialog>` hides the backdrop when the dialog has `display: none`, while the IE/Edge impl for fullscreen still shows the backdrop even if the fullscreen element is not displayed.

It seems to me that the current spec implies the behavior of IE/Edge, but I don't see it makes much sense to do so.

I don't believe it would be common to show only the backdrop. Even if authors really want to do so, they can always apply `visiblity: hidden` to the corresponding element to effectively hide the element.

In addition, it seems to me that not rendering `::backdrop` when the element does not have layout box is easier to impl.

Thus I propose that, `::backdrop` should not be rendered if the corresponding element, or an ancestor, has `display: none`.

**Comment by annevk** [comment]
That makes sense to me.

**Comment by foolip** [comment]
:+1:

**Comment by annevk** [comment]
Thank you!
