### ISSUE TITLE
Compute sticky position?

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#21]
In spite of my proposal in #19, should we also recompute `position: sticky` to `absolute`? I guess we should. `sticky` is somehow a mix of `relative` and `fixed`, and it makes the element always in-flow, which doesn't seem to make sense for top layer.

**Comment by foolip** [comment]
Can you elaborate a bit on the implications of this?

**Comment by upsuper** [comment]
I think the spec should just say
> If its specified position property is **anything other than fixed and absolute**, it computes to absolute.

**Comment by annevk** [comment]
@foolip objections?

**Comment by foolip** [comment]
No, that sounds OK. I haven't checked where such fixups to the computes style are done in Blink, but the spec already says things like this.
