### ISSUE TITLE
Specify behavior of popovers with fullscreen API

### ISSUE THREAD

**Issue by nt1m** [whatwg/fullscreen#216]
Currently `showModal()` cannot be called on dialogs that are popovers to avoid conflicting elements in the top layer.

In a similar fashion, you shouldn't be able to request fullscreen on popovers. I assume this was an oversight since the fullscreen spec is separate.

**Comment by annevk** [comment]
cc @josepharhar @mfreed7

**Comment by nt1m** [comment]
Fixed by #204
