### ISSUE TITLE
Consider removing the containing block adjustment for popovers

### ISSUE THREAD

**Issue by nt1m** [whatwg/fullscreen#218]
Popovers currently have their containing block adjusted as the result of going into the top layer. This behavior feels a bit unexpected, I started to use `position: relative` on a container, so I could use `top/left/right/bottom` positioning relative to the container on the popover, but I remembered only later that it doesn't work because of the top layer containing block adjustment. I know this use case is supposed to be achievable with the CSS anchored positioning API, but I wouldn't be surprised if web developers would be surprised about this behavior.

@mfreed7 @josepharhar What do you think?

**Comment by nt1m** [comment]
I think the adjustment feels more natural for fullscreen/modal dialogs however, since they are clearly visually separated from the rest of the page.

**Comment by nt1m** [comment]
(Also the top layer definition should really be moved to CSS at some point)

**Comment by mfreed7** [comment]
Hmm, I really think popover top layer behavior (including this containing block adjustment) should follow the other top layer things like dialog and fullscreen. This is a key use case for popover, actually: one of the big hassles with userland popovers is that the popover usually has to be parented to some element placed at the end of the `<body>`, to avoid containing block problems like ancestor clipping or transforms. The top layer nicely solves that, allowing popover content to be DOM-located next to the invoker and the rest of the content, which is convenient, but also good for a11y.

This is precisely what the [anchor positioning API](https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/) is built to solve.

**Comment by nt1m** [comment]
>  This is a key use case for popover, actually: one of the big hassles with userland popovers is that the popover usually has to be parented to some element placed at the end of the <body>, to avoid containing block problems like ancestor clipping or transforms. 

Makes sense!
