### ISSUE TITLE
Fullscreen on non-HTML elements?

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#22]
Should fullscreen request be allowed on non-HTML elements?

It seems impls disagree with each other. IE/Edge treats it as an error to request fullscreen on inner SVG elements. Firefox and Chrome, on the other hand, do allow requesting fullscreen on such kind of elements. They do make the window fullscreen, but the target element does not actually become fullscreen at all.

As of Gecko, inner SVG and MathML elements are not allowed to be out-of-flow. I didn't find any spec mentions whether they can or cannot be out-of-flow, but the current behavior looks reasonable. However, that means the fullscreen stylesheet just makes no sense for those elements.

Thus, I tend to think requesting fullscreen on non-HTML elements should be an error.

Thoughts?

**Comment by annevk** [comment]
Should we only allow it for `<svg>` and `<math>`? It seems simpler to just allow it, even though it doesn't always create the best results. Perhaps the stylesheet can be iterated on over time.

@fantasai, @tabatkins, thoughts?

**Comment by upsuper** [comment]
Yeah, `<svg>` and `<math>` are fine. Only inner elements seem to be problematic.

**Comment by foolip** [comment]
OK with me to allow it, but if this is tricky for any implementor I'd be equally fine with disallowing it.

**Comment by tabatkins** [comment]
Same - having the outermost <svg> or <math> fullscreenable sounds fine, but disallowing all the inner elements is good.

**Comment by annevk** [comment]
So how should we fix this, only extend the classes of the relevant elements? Does `<math>` even have a class?

**Comment by upsuper** [comment]
I propose this way: if the element has a parent, and the parent is not an HTML element, reject the fullscreen request.

I'm not sure whether it works for foreign object inside SVG, though.

**Comment by foolip** [comment]
What is the common property of the elements that we want to allow? That they are part of the CSS box model?

**Comment by upsuper** [comment]
The elements which `position: fixed` takes effect.

**Comment by foolip** [comment]
Is that the same set of elements on which `offsetTop` and friends make sense? There's a bug that these are supported for SVG in Blink, and I suspect that the elements where they might actually work are the same as those we're discussing here.

**Comment by upsuper** [comment]
It seems no. According to [the CSSOM View spec](https://drafts.csswg.org/cssom-view/#extensions-to-the-htmlelement-interface), `offsetTop` is an attribute of `HTMLElement`. While according to [the SVG 1.1 spec](http://www.w3.org/TR/SVG11/struct.html#InterfaceSVGSVGElement) the outer `<svg>` is an `SVGElement`.

**Comment by foolip** [comment]
Yes, but the set of elements where it makes sense is not the same set of elements where these attributes are supported per spec, in particular they would make sense for `<svg>` in HTML. That is why I ask, because I suspect that it's precisely the same set of elements, and that the property that they share is they are part of the CSS box model.

**Comment by upsuper** [comment]
Then I guess probably yes.

**Comment by annevk** [comment]
Maybe we should stick with HTMLElement for now?

**Comment by foolip** [comment]
Sure, but since this now returns a promise maybe check it in prose instead of extending `HTMLElement`, so that it's a rejected promise instead of an exception due to a missing function.

**Comment by annevk** [comment]
Hmm, I guess if we do that we can allow `<math>` and `<svg>` too. Okay, element in the HTML namespace or one of them.
