### ISSUE TITLE
Suggestion to Add Translated Link for fullscreen (Simplified Chinese 简体中文)

### ISSUE THREAD

**Issue by JinDX** [whatwg/fullscreen#239]
### What is the issue with the Fullscreen API Standard?

I have completed the translation of the fullscreen specification into Simplified Chinese (简体中文). Here is the link to the translated document:

- [Translated version of the specification in Simplified Chinese](https://htmlspecs.com/fullscreen)

It would be helpful for international users if this link could be added to the official documentation or the README.

Thank you for considering this request!

**Comment by annevk** [comment]
Thank you! It's live: https://fullscreen.spec.whatwg.org
