### ISSUE TITLE
::backdrop of root

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#24]
From the current spec, if we make the root element fullscreen, it would have a black background, because root has a transparent background by default, and the `::backdrop` will then provide the background color.

It doesn't match any current implementation, and it doesn't really make sense to me.

I propose that we change `*|*:fullscreen::backdrop` in the default style sheet to `*|*:not(:root):fullscreen::backdrop`.

**Comment by annevk** [comment]
Every element has a transparent background by default though. And if we make the root element special, should we make the body element special too given how it's special in CSS and for certain events and such?

**Comment by upsuper** [comment]
I think all impls currently agree with the behavior that, when root goes fullscreen, it still has white background, while when body goes fullscreen, it just turns to the black background like other normal elements.

I suspect the current behavior is because we previously wrote the background in the `:not(:root):fullscreen` declaration? And thus I guess this behavior was unintentionally changed when we introduced `::backdrop`.

I suggest we just bring the current behavior all impls agree with back to the spec again.

**Comment by foolip** [comment]
I agree, it's a bit odd to have `:not(:root):fullscreen` for the "make it big" rules but just `:fullscreen::backdrop` for the background color.
