### ISSUE TITLE
`position` value of `::backdrop` pseudo-element

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#27]
The spec says
> An element in a top layer has the following characteristics:
> ...
> * If its specified position property is static or relative, it computes to absolute.

But it doesn't mention whether that should happen for `::backdrop` pseudo-element.

I think for `::backdrop`, we should either also compute non-absolutely position values to `absolute`, or make the `position: fixed` rule be `!important`.

**Comment by upsuper** [comment]
Probably we should just say
> An element in a top layer **and its corresponding `::backdrop` pseudo-element if any** have the following characteristics:

**Comment by annevk** [comment]
And then reword the sentence that calls out `::backdrop`? Works for me. @foolip?

**Comment by upsuper** [comment]
BTW, I guess we can make
```css
position:fixed;
top:0; right:0; bottom:0; left:0;
```
apply to all `::backdrop`.

It seems `dialog::backdrop` uses the same values for these properties.

**Comment by upsuper** [comment]
Wait... I didn't see there is a sentence in `::backdrop` section says:
> This pseudo-element box has the same characteristics as any element box in the top layer.

So I guess it is actually not an issue.

**Comment by annevk** [comment]
Well, we made that change about `display:none` that's duplicitous given this, no?

**Comment by foolip** [comment]
So, um, what is the problem that now remains?

**Comment by annevk** [comment]
"It, and its ::backdrop pseudo-element, are not rendered if its inclusive ancestor has the display property set to none." is a duplicate if `::backdrop` already has the same requirements. I think we should fix this as suggested by @upsuper above, instead of having the `::backdrop` section act as if it were an element for the purposes of this section.

**Comment by upsuper** [comment]
Probably not completely a duplicate? If we do
> It, ~~and its ::backdrop pseudo-element,~~ are not rendered if its inclusive ancestor has the display property set to none.

Then it is not clear whether the pseudo-element should be rendered if the top layer element has `display: none`, because `::backdrop` doesn't seem to be a descendant of the element, does it?

**Comment by foolip** [comment]
They way it's phrased, the "its" in "its inclusive ancestor" refers to just the element, not the pseudo-element, so I don't think that's a problem.
