### ISSUE TITLE
Fullscreen element with `display: contents`

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#28]
The CSS Display Module Level 3 spec adds a new value to `display` property which is [`contents`](https://drafts.csswg.org/css-display-3/#box-generation). It is currently only supported by Firefox.

This value, like `none`, doesn't generate any layout box for the element, and is not affected by the `position` value. So if requesting fullscreen on element with this setting, it is not possible to render this element in the top layer.

In this case, I suggest that the element should be rendered normally as if it is not in the top layer, and the `::backdrop` pseudo-element should not be rendered.

Not sure what the spec should say.

**Comment by annevk** [comment]
@tabatkins?

**Comment by tabatkins** [comment]
I think the two reasonable options are (1) ignore the fullscreening (I guess it still is fullscreened per the API, but no special rendering) or (2) force it to generate a block box.

**Comment by annevk** [comment]
I like treating it as 'block' for elements in the top layer better myself. Forcing it out of the top layer seems rather involved.

**Comment by upsuper** [comment]
I'm fine either way. But if we want to force it to generate a block box, we should change the computed value of that property according, and this behavior should be explicitly mentioned in both spec, I suppose.

**Comment by foolip** [comment]
Would that amount to adding `*|*:not(:root):fullscreen { display: block !important; }` to the UA style sheet, or special rules for the computed `display` property at some other point?

**Comment by annevk** [comment]
I was thinking just special rules for `display` in the top layer thingie.

**Comment by upsuper** [comment]
I don't think we should ever force `display` value of fullscreen element to a single value, because fullscreen element can be a container, and thus, unlike backdrop, different display values are useful for fullscreen element.

**Comment by foolip** [comment]
> I was thinking just special rules for `display` in the top layer thingie.

OK, I was worried that this might be a performance issue if there wasn't any/much existing stuff like this, but it looks like there's already some style adjustment for top layer in Blink, so it shouldn't be a problem.

**Comment by tabatkins** [comment]
> I don't think we should ever force display value of fullscreen element to a single value, because fullscreen element can be a container, and thus, unlike backdrop, different display values are useful for fullscreen element.

Right, setting it to `block` or whatever *at all times* is def wrong; it'll break things all over the place.  It's just a decent default for what to do when you have to force it to generate a box.

**Comment by annevk** [comment]
@upsuper can't we just set it 'block' in the top layer when it would otherwise compute to 'contents'?

**Comment by upsuper** [comment]
I think it's fine to compute `contents` to `block` if the element is in the top layer.

I tend to respect the original value and the rule in the CSS spec (thus the proposal in comment 0), but if that adds much more complexity to this spec, I don't think it's worth.

In respect of implementation, both are fine.
