### ISSUE TITLE
Issues with the removing steps

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#29]
In the current spec, the substep 2.1 is:
> If node is its node document's fullscreen element, exit fullscreen that document **and terminate these steps.**

The bold part should be removed, because we have removed the hierarchy restriction, and thus we may continue reaching other elements in the top layer after exiting fullscreen from the current fullscreen element.

In addition, I believe this removing steps should cover the whole top layer, instead of only fullscreen elements.

(BTW, I wonder what would happen if I request fullscreen on a model `<dialog>` or make a fullscreened `<dialog>` modal...)

**Comment by annevk** [comment]
Well, the removing steps have to be specific per type of thing right? I can imagine `<dialog>` having similar requirements of course.

Removing the bold part seems fine.

**Comment by foolip** [comment]
> Removing the bold part seems fine.

Yep.
