### ISSUE TITLE
The "fully exit fullscreen" algorithm and nested fullscreen document

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#3]
It seems to be unclear what should happen when we fully exit fullscreen on a document which includes nested fullscreen document.

Consider the following case:
* div id=a
  * div id=b
    * iframe
      * div id=c

If we do:
1. request fullscreen on #a 
2. request fullscreen on #b 
3. request fullscreen on #c 
4. fully exit fullscreen

According to the algorithm, it seems to me that #b as well as the iframe inside will be directly removed from the fullscreen stack before performing `exitFullscreen()`. It is clear that the outer document will exit fullscreen and get a fullscreenchange event, but it is not clear what happens to the inner document.

It seems to me that the algorithm of `exitFullscreen()` could handle this properly, as it collects "descendant browsing contexts' documents with a non-empty fullscreen element stack", and the iframe removed from the fullscreen stack still have a non-empty fullscreen element stack, hence will also exit fullscreen state and get the fullscreenchange event.

But I think it is worth a note in the section of "fully exit fullscreen" which mentions that even if a nested document is removed from the stack in step 3, it still keeps its fullscreen element stack, and consequently could be handled by `exitFullscreen()`.

**Comment by annevk** [comment]
No, per https://fullscreen.spec.whatwg.org/#fully-exit-fullscreen step 3 the idea is that only the iframe remains (top) and a/b are removed. Does that need to be clarified?

**Comment by upsuper** [comment]
Then it looks like that the steps will leave the subdocument still in fullscreen state while its container element is no longer in fullscreen, which seems to be unfortunate.

**Comment by upsuper** [comment]
It seems to me the step 3 doesn't do anything special to the iframe?

**Comment by annevk** [comment]
"Unfullscreen elements within doc until only the top element is left." The top element is iframe, no?

**Comment by upsuper** [comment]
Why is the top element the iframe? Isn't that #a?

**Comment by annevk** [comment]
The top element is the one rendered closes to the user per https://fullscreen.spec.whatwg.org/#new-stacking-layer

**Comment by upsuper** [comment]
Ahh... ok. When it comes to removing something from a stack, I always assume it starts from the top of the stack, hence that step was interpreted as poping out elements until only the last one left.

Probably clearer to say something like "Unfullscreen all elements except the current top element".

**Comment by foolip** [comment]
Oh, didn't see this issue until now. More confusion in https://github.com/whatwg/fullscreen/issues/10 :)
