### ISSUE TITLE
What should happen if an element is moved to another document right after requestFullscreen

### ISSUE THREAD

**Issue by smaug----** [whatwg/fullscreen#33]
Unless I'm missing something, this should just work per spec, but feels odd.
For other cases there is "Whenever the removing steps run with an oldNode, run these steps"

**Comment by foolip** [comment]
The answer should probably be the same as when moving *within* a document, as otherwise extra bookkeeping will be required to distinguish the two cases.

**Comment by annevk** [comment]
If it's moved to another document, aren't the removing steps run?

**Comment by smaug----** [comment]
They are, but I don't see them doing anything in this case, unless I'm missing something.

**Comment by annevk** [comment]
Hmm, I guess the element simply goes fullscreen in the new document, but that seems a little weird.

**Comment by foolip** [comment]
I think that regardless of where the element is moved, having it just work seems better than the extra bookkeeping to prevent it. The fullscreen element ready check is re-run after the resize, so even if the element moved into a document with no `allowfullscreen` attribute, no interesting invariant would be upheld by failing on move.

**Comment by foolip** [comment]
@upsuper, what kind of bookkeeping to make this fail do you have in mind?

**Comment by upsuper** [comment]
In Gecko, we handle fullscreen request in document, and the document checks whether the element's owner doc is itself as part of the fullscreen element ready check.

I think the main issue of allowing element to go fullscreen in a different document is that, at the moment of "the next animation frame task", the window of the previous document may have been made fullscreen, and the new document may not in the same window (or same tab) as the original document, which would confuse the browser.

It is probably fine enough to say it should fail if the two documents are in different top-level browsing contexts. But I'd prefer making it simple (and keep our current impl as-is :) via just saying it should fail when the element is moved to a different document.

**Comment by foolip** [comment]
I'd be OK with requiring that the document is the same if that makes things easier for Gecko. Care to draft a PR? I think it'd be simplest to just check the document in the animation frame task, which means the element would be allowed to move to another document and back.

**Comment by foolip** [comment]
https://github.com/whatwg/fullscreen/pull/64 keeps track of the original *topLevelDoc*, which isn't quite the same as keeping track of the node document. @upsuper, are pending Fullscreen requests in Gecko tied to each individual document, a tab-wide manager of sorts?

Blink has some state attached to the documents, but I'm trying to change things so that pending requests go into a single queue, although still in the same process as the documents. With per-document book keeping, I can't see how to get the order of requests right, if the same script requests fullscreen in two iframes for example.
