### ISSUE TITLE
An editorial nit in "fullscreen element ready check"

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#4]
The third line:

> element's node document's top layer contains no elements whose fullscreen flag is or its top element is an inclusive ancestor of element, which has its fullscreen flag set. 

should probably be

> element's node document's top layer contains no elements whose fullscreen flag is **set** or its top element is an inclusive ancestor of element, which has its fullscreen flag set.

**Comment by annevk** [comment]
This was fixed as part of https://github.com/whatwg/fullscreen/commit/61ae1df2133d9caf5e6d1742a6f58b2c43bd5bec no? Are you looking at a cached copy?

**Comment by upsuper** [comment]
Ah, yeah... Probably I was looking at an old copy.
