### ISSUE TITLE
Use new "allowed to use" algorithm once introduced

### ISSUE THREAD

**Issue by annevk** [whatwg/fullscreen#41]
Once https://github.com/whatwg/html/pull/1492 lands "fullscreen enabled flag" is no longer a thing.

**Comment by foolip** [comment]
It has landed. Should it be a new concept "fullscreen enabled check" that says "return true if *document* is *allowed to use* the feature indicated by attribute name `allowfullscreen`" or some such? Seems a bit cumbersome :)

**Comment by annevk** [comment]
We only check it twice so we can probably repeat that sentence twice. Interested in writing a PR?
