### ISSUE TITLE
Element moved into another document after requesting fullscreen should make the request fail

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#59]
If an element requests fullscreen, then it is moved to another document, especially if it is moved to a document inside a different top-level browsing context, it is not reasonable to require browser to handle that properly.

I think we should just reject the fullscreen request if the element is moved to a different document

**Comment by foolip** [comment]
Closing in favor of https://github.com/whatwg/fullscreen/issues/33 which is very similar.
