### ISSUE TITLE
Inconsistency of condition between entering fullscreen and exiting fullscreen

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#6]
In conditions of "fullscreen element ready check", the spec says:
> element's node document's top layer contains **no elements whose fullscreen flag is set**, or ...

However in the steps of "collect ancestors":
> While docs's last document has a browsing context container whose node document's top layer **consists of a single element and that single element has its fullscreen flag set**, append that node document to docs.

It means, when we have something in the top layer but nothing is fullscreened yet, it is possible to put an element into fullscreen, because there is no element in the top layer with fullscreen flag set, but we cannot exit fullscreen on this document in this case, because when we collect ancestors, the top layer contains more than a single element, although other elements do not have fullscreen flag.

**Comment by upsuper** [comment]
We have two ways to resolve this issue. The stricter one is to change the ready check condition and disallow any element to enter fullscreen if there has been something in the top layer which does not have fullscreen flag.

The looser one is to change the "collect ancestors" step and make it collect a document if the top layer contains only one element which has fullscreen flag set.

I guess the stricter one makes more sense given the current spec where it is not allowed to have discontinuity between fullscreen elements in the top layer.

**Comment by annevk** [comment]
@foolip do you agree?

**Comment by upsuper** [comment]
I think @foolip probably wants a looser rule than "the looser one". IIRC he always wants not to add restriction on what element can be made fullscreen, but I suspect that could potentially complicate impl with little gain.

**Comment by foolip** [comment]
I agree something is strange here, and filed a few similar issues.

As for "element's node document's top layer contains no elements whose fullscreen flag is set, or its top element is an inclusive ancestor of element, which has its fullscreen flag set," is there any reason we can't just allow any kind of crazy order to fullscreen requests now?

It would be odd, I think, if a sibling `<dialog>` of the fullscreen element could appear on top of it by entering the top layer stack, but a sibling `<div>` cannot by requesting fullscreen.

**Comment by annevk** [comment]
I would be interested to hear from @upsuper what the implementation complexity is with allowing more.

**Comment by annevk** [comment]
Is it still added complexity if Gecko supports `<dialog>`?

**Comment by upsuper** [comment]
I think I'm fine with requesting fullscreen in any order from the perspective of impl. I'm more concerned about the complexity of the spec and whether the behavior would make sense to authors.

Anyway, I suggest we at least persist with the restriction that fullscreen elements must be put continuously in the top layer stack, and can only be put from the bottom of the stack. It seems to be less risky.

**Comment by foolip** [comment]
>  fullscreen elements must be put continuously in the top layer stack, and can only be put from the bottom of the stack

Can you elaborate on what this means in terms of a spec change? I'm not sure I understand.

**Comment by upsuper** [comment]
I mean, the "fullscreen element ready check" contains something like:
> element's node document's top layer is empty, or the topmost element in the top layer has fullscreen flag set.

**Comment by foolip** [comment]
OK, so basically eliminating the case where a sibling of an active `<dialog>` goes fullscreen?

If we want this kind of invariant, could it make sense for it to apply to the top layer system as a whole and not just fullscreen? The invariant would be that when adding an element to the top layer, the top layer must either be empty, or its top element must be a non-inclusive ancestor of the element being added.

**Comment by upsuper** [comment]
I want to avoid fullscreen elements covering anything else in the top layer, e.g. dialog.

I don't think it is necessary to be a common rule in the top layer system. I believe it makes sense to have dialog on top of fullscreen element, but not versa vice.

BTW, I don't think I mentioned anything about the hierarchy requirement in my last comment. I just said the topmost element in the top layer must have fullscreen flag set.

**Comment by foolip** [comment]
I see, you want to prevent the case where a child of an active `<dialog>` goes fullscreen as well. That is what your definition does, but I was thinking about siblings only.

`<video>` inside a `<dialog>` doesn't seem too far-fetched to me, ads in dialogs seem pretty common on mobile and I don't know why video ads might not end up there. Not being able to watch that video in fullscreen seems odd.

**Comment by upsuper** [comment]
If that case, we would need to apply hierarchy restriction you mentioned to the whole top layer. Otherwise we would again meet issues like what I described in [bug 27865](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27865#c0).

Actually I feel this way is probably safer, as the elements in the top layer are strictly controlled in the same order in all places. But it is more restricted, which I guess you don't like.

**Comment by foolip** [comment]
I think that sounds good actually, it's not that I want no restrictions, it's that the `<dialog>` and fullscreen now seem quite similar so having different rules for them make the model harder to understand.

Does that sound OK to you, @annevk?

**Comment by annevk** [comment]
You mean whether this is okay:

> The invariant would be that when adding an element to the top layer, the top layer must either be empty, or its top element must be a non-inclusive ancestor of the element being added.

That is okay with me. Does `<dialog>` have some kind of failure mode currently? How would we best define this?

**Comment by foolip** [comment]
Yep, that's the invariant I mean. I couldn't find any restrictions like that in https://html.spec.whatwg.org/#the-dialog-element but I suppose what would make sense is that there's something like a "top layer element ready check" and that HTML checks this and handles the failure before adding things to the stack.

BTW, the "move if already present" bit in the current spec ought to become dead code with such a change.

**Comment by annevk** [comment]
Okay that seems fine. @Hixie, does that work for you?

**Comment by annevk** [comment]
(He thought we already had this restriction. Will add it to the specification.)

**Comment by annevk** [comment]
Hmm, so @Hixie thinks it might be common to have sibling dialogs.

**Comment by foolip** [comment]
But is it common to want to show one "inside" the other, so that closing it goes back to showing the first? If not, HTML could arrange to close dialogs that would be "misnested" by our definition.

**Comment by foolip** [comment]
(I mean in cases of sibling dialogs of course, dialogs that are nested in the DOM are a non-issue.)

**Comment by annevk** [comment]
> it'll presumably be common to have sibling `<dialog>`s
> where one ends up on top of the other
> e.g. if you have a page-global "message box" dialog
> and another dialog tries to use it

**Comment by foolip** [comment]
Hmm, so I guess you'd put `<dialog>` anywhere in the DOM (it won't be rendered if closed) and then `show()` it without any concern about the shape of the DOM tree. Makes sense, I suppose.

So, given that it could make sense to have fullscreen inside dialogs and dialogs in fullscreen, are we left with any restrictions that would actually uphold an invariant? If an element is in fullscreen and a sibling `<dialog>` can be made to completely obscure the fullscreen element, then it's effectively already possible to do "fullscreen" with weird nesting, just with a strange API.

**Comment by annevk** [comment]
I guess we should just remove the restrictions and explain why in a note.

**Comment by foolip** [comment]
I would be OK with that. I take it even the implied "*element*'s node document's fullscreen element is not *element*" requirement would go away to, so that requesting fullscreen on the same element twice just works, and fires just one `fullscreenchange` event?

**Comment by annevk** [comment]
Yeah.

**Comment by foolip** [comment]
@upsuper, so that I'm not missing something, do you think this would create havoc in cases like [bug 27865](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27865#c0)?

**Comment by upsuper** [comment]
Wait... What's the decision now? Remove any restriction on hierarchy? Doesn't that still produce unfortunate result for case 3 I mentioned in [bug 27865](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27865#c0)?

**Comment by annevk** [comment]
Yes it would. New proposal: `requestFullscreen()` errors for elements marked inert.

**Comment by upsuper** [comment]
OK, that makes sense.

**Comment by foolip** [comment]
Hmm, is this a case that we've seen in the wild? It'll presumably still be possible to have an inert child of the fullscreen element so that nothing can be clicked anyway.

**Comment by annevk** [comment]
I think we're just trying to anticipate problematic scenarios. It's easier to have the check for now and remove it later than the other way around.

**Comment by foolip** [comment]
It looks like in the case of two competing `showModal()` calls, the last one just wins, so that the first one is still open but inert:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3565

Could the same be done for fullscreen, perhaps by defining that the top element in the top layer stack is never inert?

**Comment by foolip** [comment]
I mean, practically speaking there is no problem here, I'm just trying to maximize the commonality between dialog and fullscreen, since it ought to lead to more code sharing when implemented.

**Comment by upsuper** [comment]
Hmm, there are still cases which could cause problematic scenarios, but probably mostly because of the HTML spec.

For example, in document:
* dialog id=a
* div id=b
* dialog id=c

Run the following steps:
1. call `showModal()` on #a 
2. call `requestFullscreen()` on #b 
3. call `showModal()` on #c 
4. call `close()` on #c 

According to HTML spec, now #a will block the document, however #b is still the top element in the top layer.

We probably should also change HTML spec and merge the "pending dialog stack" into the top layer.

**Comment by foolip** [comment]
Oh, are all elements in the "pending dialog stack" not always also in the top layer? The HTML spec says "When an element is added to the pending dialog stack, it must also be added to the top layer layer. When an element is removed from the pending dialog stack, it must be removed from the top layer." so I'm not sure how...

**Comment by upsuper** [comment]
I think the spec intend to ensure that elements in the "pending dialog stack" are always in the top layer, breaking that should be a problem of the HTML spec. (Actually it seems to me there are several cases it can be broken, but I'd rather discuss them in the place for that spec instead of here.)

**Comment by upsuper** [comment]
Also, I guess we probably would have some fun with calling both `showModal()` and `requestFullscreen()` on a same element in some order :)

**Comment by foolip** [comment]
File HTML bugs at https://whatwg.org/newbug :)

It seems like even if fullscreen is careful to not interact badly with `<dialog>`, if the reverse case isn't handled by the HTML spec, then the end result is going to look rather arbitrary. (I think it's likely that whatever we now come up with will be the final state, nobody will come along and clean up the edge cases later.)

**Comment by upsuper** [comment]
I guess what we probably can do is to move the blocking document concept from the HTML spec to top layer, so that the top element in the top layer stack always blocks the document.

BTW, as the top layer interacts with both rendering and the object model, I guess it proably should live in its own spec instead of being a chapter of the Fullscreen API spec.

**Comment by foolip** [comment]
Do you mean the [blocked by a modal dialog](https://html.spec.whatwg.org/#blocked-by-a-modal-dialog) concept? `HTMLDialogElement.show()` isn't modal and doesn't trigger that, right?

**Comment by upsuper** [comment]
Yes. Right.

**Comment by foolip** [comment]
So non-modal dialogs don't cause the rest of the document to be inert, but maybe it would actually be a good idea if fullscreen did, because it's very weird if you make your fullscreen element transparent and then interact with the page below it...

**Comment by upsuper** [comment]
It seems to me that non-modal dialogs do not use top layer at all.

**Comment by foolip** [comment]
You're right, it doesn't in the spec nor in Blink's implementation, I was fooled by the rather similar rendering.

Given that, it seems pretty reasonable to say that whenever the top layer stack is non-empty, everything except the top element is inert. When trying to add something that is inert to the top layer, there are two options:
1. Just do it, which is apparently what `showModal()` does.
2. Fail with an exception, error event or rejected promise depending on the API.

Preferences?

**Comment by upsuper** [comment]
I guess 1 is probably the safer one, because it seems to me that that would make it harder to run into trouble that an element is blocked by something invisible.

**Comment by upsuper** [comment]
Also it is probably safer to move the "add, or move if already present" phase from "fullscreen an element" to something like pushing to top layer, so that we won't have undefined behavior even if the user of this concept accidentally allows adding an element multiple times.

**Comment by foolip** [comment]
Might be worth checking if it's intentional by @Hixie to allow nested modal dialogs like this, but if it is, having virtually no restrictions and just making it work seems reasonable to me.

**Comment by Hixie** [comment]
I'm not sure I exactly understand the case that's at issue here, but it's definitely intended that you can have a child of &lt;body> that is a &lt;dialog> that asks for, say, a pizza preference, make that modal, then have another child of &lt;body> that is a &lt;dialog> that is a message box, and have that be fired and modal on top of the other one, saying, say, "we cannot bake pizzas with chocolate ice cream", and for both of these dialogs to be able to have subparts made full-screen while they are the dialog on top.

**Comment by foolip** [comment]
Thanks, @Hixie! There's no known problem here, just trying to have `showModal()` and `requestFullscreen()` share as much logic as possible.

So the plan is:
* No hierarchy restrictions for `requestFullscreen()`.
* A non-empty top layer stack is what makes every other element inert.
* Some shared algorithms for manipulating the top layer stack might be nice.

Does that sound about right?

**Comment by Hixie** [comment]
I don't see any obvious problem with that off the top of my head.

**Comment by upsuper** [comment]
@annevk I think you forgot to add the "blocked by top layer element" concept.

**Comment by annevk** [comment]
Right, I discussed with @foolip on IRC and the idea was that HTML would define that bit since it already defines the whole inertness concept.

**Comment by annevk** [comment]
I filed #15 to keep track of that. If you'd like that to be solved in a different way we can discuss it there. Hope that's okay.
