### ISSUE TITLE
Define what happens with requestFullscreen() and exitFullscreen() in inactive document

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#67]
From @zcorpan in https://bugs.chromium.org/p/chromium/issues/detail?id=674454

I don't think we should fire any events, because I don't know how to implement it. (In Blink, in an inactive document, events are just dropped on the ground.)

Just rejecting the promise would work, though.

Also need to define what happens if the document becomes inactive between the request and the animation frame task.

**Comment by zcorpan** [comment]
Oh right, the event loop doesn't spin in inactive documents. We can still queue to fire the event, though. If the document becomes active again, it would be fired at that time, right?

**Comment by foolip** [comment]
Is that if one navigates back and forward?

**Comment by zcorpan** [comment]
Yeah. Or just navigate to a new doc, request fullscreen in the inactive doc, then navigate back.

**Comment by foolip** [comment]
So for `requestFullscreen()` is this covered by "If document's browsing context's active document is not document, then return false." in https://html.spec.whatwg.org/multipage/embedded-content.html#allowed-to-use?

**Comment by zcorpan** [comment]
Yes.
