### ISSUE TITLE
The display type of ::backdrop pseudo-elements

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#8]
It seems it is not explicitly defined what the display type of ::backdrop pseudo-elements. The default value of "display" in CSS spec is "inline" [1] which doesn't seem to be a proper value for that pseudo-element. I think it should use "block" instead.

Also, other than complicating the impls, I don't see it makes any sense to allow using other display type on ::backdrop.

For these reasons, I propose that we specify "::backdrop { display: block !important; }" in the default style sheet.

[1] http://dev.w3.org/csswg/css-display-3/#the-display-properties

**Comment by foolip** [comment]
Makes sense.
