### ISSUE TITLE
User agent needs latitude to end fullscreen when needed

### ISSUE THREAD

**Issue by avidrissman** [whatwg/fullscreen#93]
Right now, there doesn't seem to be any leeway in the spec for the user agent to unilaterally decide to end fullscreen for an element. 

I know that we do this already in Chromium: if a page spawns a pop-up window, we drop fullscreen. I'm arguing in a [Blink Intent](https://groups.google.com/a/chromium.org/d/msg/blink-dev/waIh70rrNKM/YzfvTGLvBgAJ) that the same should be done for when a page spawns a dialog. But whatever your position is on that particular Intent, surely the ability for a UA to decide that in certain situations, it needs to force an end to fullscreen needs to be there.

@foolip suggested in a post as one of a list of options:

> Something more handwavy in https://fullscreen.spec.whatwg.org/#ui giving the UA a license to exit whenever it thinks it's in the best interest of the user.

The other option was a specific one about the Intent, but I think this wider option is appropriate.

**Comment by avidrissman** [comment]
+@domenic, my HTML spec friend.

**Comment by domenic** [comment]
Personally I think we should give UAs the license to do this in any case for UX reasons.

We could go a step further though and try to get cross-browser agreement on specific points at which you fully exit fullscreen, e.g. the JS dialogs or window.open() or window.print() or similar, and then code those into the HTML spec. If we do that we can then write cross-browser web platform tests for it.

I'll let @foolip, as the fullscreen spec person, pursue one of these directions.

**Comment by foolip** [comment]
@avidrissman, would you like to prepare a PR with the change you'd like to see?

I'll be OOO for the rest of the week, but want to help get this done.

**Comment by avidrissman** [comment]
I'm OOO next week and didn't get to this this week.

I'm not familiar with standardese, so I'm not sure how good I'd be for drafting a PR.

**Comment by foolip** [comment]
I'll try to suggest something next week.

**Comment by avidrissman** [comment]
I uploaded a quick PR at https://github.com/whatwg/fullscreen/pull/95 . I'm not fluent in standards-ese, so let me know what you think.

This change is a starting point; I have no personal attachment to the phrasing used.

**Comment by upsuper** [comment]
> Personally I think we should give UAs the license to do this in any case for UX reasons.

I agree with this.

> We could go a step further though and also try to get cross-browser agreement on specific points at which you fully exit fullscreen, e.g. the JS dialogs or window.open() or window.print() or similar, and then code those into the HTML spec. If we do that we can then write cross-browser web platform tests for it.

This would definitely make the web more developer-friendly... although the reason described in the Blink intent doesn't really apply to other browsers, e.g. Firefox or Safari.

In these browsers, even if you open the JS dialog, user can still move pointer to the top to get informed that they are in fullscreen, and how they can exit it. And in Firefox, when you press esc, you can reliably exit fullscreen state no matter what is shown, so this wouldn't add much value to security for us.

But those are really kind of impl-decision, so if some browsers use a different way for such thing, I think this is a reasonable license to give.

**Comment by upsuper** [comment]
Thought about this for another second. This can potentially lead to webcompat issue in the future, actually.

I mean, if poping up dialog leads to exiting fullscreen in Chrome, could websites rely on that in the future in some case that they should really use `exitFullscreen`? e.g., if a website enters fullscreen, and pop up a dialog, and the developer tests it on Chrome and finds it exits fullscreen, then they may assume it would just exit fullscreen everywhere. In that case, other browsers would be left in fullscreen while the page thinks it has exited.

**Comment by foolip** [comment]
> if poping up dialog leads to exiting fullscreen in Chrome, could websites rely on that in the future in some case that they should really use `exitFullscreen`?

It's plausible, silly things like that happen all the time on the web platform, although it's impossible to predict which specific silly things will become a problem.

We have two options:
1. Normative requirements (must) about which things should cause the UA to exit fullscreen, so that tests can be written for those cases.
1. Anything short of that, where no shared tests could be written.

If we do the first, it will mean that some UAs will have to add code to exit in places where they don't consider it to be a security precaution, for the purpose of interop.

I would be happy either way. @upsuper, between exiting for modal dialogs and new windows (like Chrome) or an interop risk, which would you prefer?

**Comment by upsuper** [comment]
I'm not particularly happy with either way actually... but I guess I'm not too concerned about the interop risk, so probably we can merge #95.

The other way is making things more restrictive, so we can always go that way whenever we find it necessary, although I hope it never becomes necessary :/
