### ISSUE TITLE
Throw NotAllowedError when not "allowed to request fullscreen"

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#97]
Following https://github.com/WICG/web-share/issues/45

https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen

Here it'll probably be necessary to make *error* either the value to throw or null, instead of a boolean.

**Comment by annevk** [comment]
What's the reason for the change though? I thought the conclusion from that thread was that "it doesn't matter".

**Comment by foolip** [comment]
Only for consistency if all other specs go that way, but I don't feel particularly strongly. @upsuper?

**Comment by upsuper** [comment]
Conceptually, I agree `NotAllowedError` fits better this case, but I'm uncertain whether it's worth complicating things for this kind of reason...

**Comment by foolip** [comment]
@mgiuca made a list of exceptions thrown in https://github.com/WICG/web-share/issues/45#issuecomment-312970624, more variety than I expected. Let's leave this open for 30 days, and if it doesn't look like all/most specs are going to move to NotAllowedError, just let it be.

**Comment by foolip** [comment]
Closing per https://github.com/WICG/web-share/issues/45#issuecomment-313625371
